apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-profile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-profile
  template:
    metadata:
      labels:
        app: spring-profile
    spec:
      containers:
      - name: spring-profile-container
        image: gcr.io/gcp-docker-kubernetes-400712/profile-service:v7
        resources:
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: spring-profile-config
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-profile-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-profile-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50