apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-login-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-login
  template:
    metadata:
      labels:
        app: spring-login
    spec:
      containers:
      - name: spring-login-container
        image: gcr.io/gcp-docker-kubernetes-400712/login-service:v2
        resources:
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: spring-login-config
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-login-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-login-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50