apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profile-config
data:
  MYSQL_DB_HOST: 'mysql-profile.default.svc.cluster.local'
  # TODO: update MYSQL_DB_USER and MYSQL_DB_PASSWORD to match the variables that you used 
  #       to install the MySQL service
  MYSQL_DB_USER: 'qinlinj'
  MYSQL_DB_PASSWORD: 'j123456'
  MYSQL_DB_PORT: '3306'
  LIST_OF_PROFILE_ENDPOINTS: 'spring-profile-service.default.svc.cluster.local, mysql-azure-profile.default.svc.cluster.local'

